### Chapter 0: Setup
Importing all necessary packages and initializing the classes

In [1]:
import numpy as np
import matplotlib.pyplot as plt

from spintronics import SpintronicCircuit
Setup=SpintronicCircuit()

### Chapter 1:
Solve #task 4a, derive the analytic ...

In [3]:
def setup0():
    # First the Normal terminals
    Setup.addNormalTerminal("Left")
    Setup.addNormalTerminal("Right")

    # Adding ferro terminals
    Setup.addFerroTerminal("F1",magnetization=[1.0,0,0])
    Setup.addFerroTerminal("F2",magnetization=[0,1.0,0])
    Setup.addFerroTerminal("F3",magnetization=[0,0,1.0])

    # Add the normal nodes, no Ferromagnetic elements yet.
    Setup.addNormalNode("N1")
    Setup.addNormalNode("N2")
    Setup.addNormalNode("N3")


    #Define the params
    P = 0
    Gr1 = 0
    Gr2 = 0
    Pap = 0

    Gn = 1.0 #For normal connectors
    GFN=[1.0,0.9,0.5,0.5]
    # Now the normal connectors, treated as Ohmic conductors
    Setup.addConductor("C0", 'NT', 'N1', 'Left', Gn)
    Setup.addConductor("C3", 'NT', 'N3', 'Right', Gn)
    Setup.addConductor("C1", 'NN', 'N1', 'N2', Gn)
    Setup.addConductor("C2", 'NN', 'N2', 'N3', Gn)

    # The F-N connectors
    Setup.addConductor('CF1', 'NT', 'N1', 'F1', GFN)
    Setup.addConductor('CF2', 'NT', 'N2', 'F2', GFN)
    Setup.addConductor('CF3', 'NT', 'N3', 'F3', GFN)


In [4]:
setup0()
Setup.finalize()
print("Conductance matrix: ", Setup.ConductanceMatrix)

Conductance matrix:  [[-0.55365285  0.07551021  0.30472572  0.12701732  0.0463996 ]
 [ 0.07185401 -0.55365285  0.05368877  0.12340758  0.30470249]
 [ 0.30470249  0.0463996  -0.475281    0.08285415  0.04132477]
 [ 0.12340758  0.12701732  0.09007363 -0.42335268  0.08285415]
 [ 0.05368877  0.30472572  0.02679289  0.09007363 -0.475281  ]]


### AHE


In [7]:
def setup_AHE():
    #setup0()
    P = 0.5
    G_F = 1
    G = 1.0
    I_g = 0.5
    # First setup magnetizations
    #setting magnetization of the nodes
    Setup.setMagnetization('T', 'F1', [-1.0,0,0])
    Setup.setMagnetization('T', 'F2', [0,-1.0,0])
    Setup.setMagnetization('T', 'F3', [0,0,-1.0])

    Setup.compute()
    print("Conductance matrix: ", Setup.ConductanceMatrix)

#First conductance matrix

In [10]:
setup_AHE()

AssertionError: Wrong code: neither node nor terminal